[package]
name = "rust_plugin_manager"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
libloading = "0.8.1"
rust_plugin = { path = "../rust_plugin" }

[build-dependencies]
cbindgen = "0.26.0"