[package]
name = "my_devkit_plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
libc = "0.2.149"
my_devkit_plugin_macros = { path = "../my_devkit_plugin_macros" }

[build-dependencies]
cbindgen = "0.26.0"